### PR TITLE
Align with current specs

### PR DESCRIPTION
**Pull request by danfowler**

### CODE REVIEW

**Comment by pwalsh** [comment]
Before merging, pls check with @vitorbaptista that there is no negative consequence to removing `base` for the current version of `datapackage-py`

**Comment by roll** [comment]
:+1: 
and agreed about checking with Vitor about `base`

**Comment by vitorbaptista** [comment]
Removing `base` shouldn't have any affect on `datapackage-py`, as we're not using it :+1:

**Comment by danfowler** [comment]
Great!  I'll merge later today then.

**Pull request merged**
